### ISSUE TITLE
Should we add `recompile` learning in Mix section?

### ISSUE THREAD

**Issue by amir-repository** [DockYard-Academy/curriculum#888]
Re run the project is taking some time and key stroke, maybe we should mention how to do it in the fast way using 'recompile' when the session is still active. and we should mention that if there's new package we should do `iex -S mix` again

Maybe insert the recompile lecture in this part will be much helpful trick for student
![Screenshot from 2023-03-14 08-01-25](https://user-images.githubusercontent.com/37258290/224865586-0c28bce6-873e-4c1a-a036-5d9d478bebe2.png)

**Comment by BrooklinJazz** [comment]
`recompile` is mentioned in the IEx reading material, so students should already be familiar with it. They also see me use it constantly (self-led students will also see me use it in video content when we add it to lessons in the future).

Starting the IEx shell also shouldn't take very long 🤔so closing it and re-opening it generally won't cost students much time. I'd rather give consistent instructions that always work rather than context-specific instructions such as `recompile()`

This suggestion is well-intentioned! But students that want to save time should already know about `recompile`.
